export const ErrorCode = {
  // Auth
  AUTH_ERROR_PASSWORD_MISMATCH: 'ERROR-AUTH-0000',
  AUTH_ERROR_OTP_INVALID_OR_EXPIRED: 'ERROR-AUTH-0001',
  AUTH_ERROR_UNAUTHORIZED: 'ERROR-AUTH-0002',
  AUTH_ERROR_RESEND_OTP_LIMIT: 'ERROR-AUTH-0003',

  // File
  FILE_ERROR_NOT_FOUND: 'ERROR-FILE-0001',
  FILE_ERROR_UPLOAD_FAILED: 'ERROR-FILE-0002',
  FILE_ERROR_INVALID_PATH: 'ERROR-FILE-0003',
  FILE_ERROR_SIZE_TOO_LARGE: 'ERROR-FILE-0004',
  FILE_ERROR_INVALID_TYPE: 'ERROR-FILE-0005',

  // Account
  ACCOUNT_ERROR_NOT_FOUND: 'ERROR-ACCOUNT-0000',
  ACCOUNT_ERROR_EMAIL_EXISTED: 'ERROR-ACCOUNT-0001',
  ACCOUNT_ERROR_INVALID_PASSWORD: 'ERROR-ACCOUNT-0002',
  ACCOUNT_ERROR_PHONE_EXISTED: 'ERROR-ACCOUNT-0003',
  ACCOUNT_ERROR_NOT_ALLOW_DELETE: 'ERROR-ACCOUNT-0004',
  ACCOUNT_ERROR_EMAIL_INVALID: 'ERROR-ACCOUNT-0005',
  ACCOUNT_ERROR_USERNAME_EXISTED: 'ERROR-ACCOUNT-0006',

  // Permission
  PERMISSION_ERROR_NOT_FOUND: 'ERROR-PERMISSION-0000',
  PERMISSION_ERROR_NAME_EXISTS: 'ERROR-PERMISSION-0001',
  PERMISSION_ERROR_CODE_EXISTS: 'ERROR-PERMISSION-0002',

  // Group
  GROUP_ERROR_NOT_FOUND: 'ERROR-GROUP-0000',
  GROUP_ERROR_NAME_EXISTS: 'ERROR-GROUP-0001',
  GROUP_ERROR_IN_USED: 'ERROR-GROUP-0002',

  OPTION_ERROR_NOT_FOUND: 'ERROR-OPTION-0000',
  OPTION_ERROR_NAME_EXISTS: 'ERROR-OPTION-0001',
  OPTION_ERROR_IN_USED: 'ERROR-OPTION-0002',

  OPTION_VALUE_ERROR_NOT_FOUND: 'ERROR-OPTION-VALUE-0000',
  OPTION_VALUE_ERROR_NAME_EXISTS: 'ERROR-OPTION-VALUE-0001',
  OPTION_VALUE_ERROR_IN_USED: 'ERROR-OPTION-VALUE-0002',

  CATEGORY_ERROR_NOT_FOUND: 'ERROR-CATEGORY-0000',
  CATEGORY_ERROR_NAME_EXISTS: 'ERROR-CATEGORY-0001',
  CATEGORY_ERROR_IN_USED: 'ERROR-CATEGORY-0002',

  TAG_ERROR_NOT_FOUND: 'ERROR-TAG-0000',
  TAG_ERROR_NAME_EXISTS: 'ERROR-TAG-0001',
  TAG_ERROR_IN_USED: 'ERROR-TAG-0002',

  FOOD_ERROR_NOT_FOUND: 'ERROR-FOOD-0000',
  FOOD_ERROR_NAME_EXISTS: 'ERROR-FOOD-0001',
  FOOD_ERROR_IN_USED: 'ERROR-FOOD-0002',
  FOOD_ERROR_OPTION_DUPLICATE: 'ERROR-FOOD-0003',
  FOOD_ERROR_TAG_DUPLICATE: 'ERROR-FOOD-0004',

  COMBO_ERROR_NOT_FOUND: 'ERROR-COMBO-0000',
  COMBO_ERROR_NAME_EXISTS: 'ERROR-COMBO-0001',
  COMBO_ERROR_IN_USED: 'ERROR-COMBO-0002',

  COMBO_GROUP_ERROR_NOT_FOUND: 'ERROR-COMBO-GROUP-0000',
  COMBO_GROUP_ERROR_NAME_EXISTS: 'ERROR-COMBO-GROUP-0001',
  COMBO_GROUP_ERROR_IN_USED: 'ERROR-COMBO-GROUP-0002',

  COMBO_GROUP_ITEM_ERROR_NOT_FOUND: 'ERROR-COMBO-GROUP-ITEM-0000',
  COMBO_GROUP_ITEM_ERROR_NAME_EXISTS: 'ERROR-COMBO-GROUP-ITEM-0001',
  COMBO_GROUP_ITEM_ERROR_IN_USED: 'ERROR-COMBO-GROUP-ITEM-0002',

  NATION_ERROR_NOT_FOUND: 'ERROR-NATION-0000',
  NATION_ERROR_NAME_EXISTS: 'ERROR-NATION-0001',
  NATION_ERROR_IN_USED: 'ERROR-NATION-0002',
  NATION_ERROR_INVALID_KIND: 'ERROR-NATION-0003',
  NATION_ERROR_INVALID_HIERARCHY: 'ERROR-NATION-0004',
  NATION_ERROR_KIND_CHANGE_BLOCKED: 'ERROR-NATION-0005',
  NATION_ERROR_HAS_CHILDREN: 'ERROR-NATION-0006',
};
